spring:
  application:
    name: ag-config
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/geek_qi/AG-Config.git

server:
  port: 8750

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/