spring:
  application:
    name: ag-auth
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/ag_auth?useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
    basepackage: com.github.wxiaoqi.learning.auth.entity
    #xmlLocation: classpath:mapper/*.xml
    mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    com.github.wxiaoqi.learning.auth.mapper: debug

server:
  port: 7777

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  expire: 3600
  pri-key:
    path: jwt/pri.key
  pub-key:
    path: jwt/pub.key

client:
  expire: 3600
  pri-key:
    path: client/pri.key
  pub-key:
    path: client/pub.key